# netlify.toml

[build]
  publish = "."

[[edge_functions]]
  function = "ip-check"
  path = "/*"

[build.environment]
  NODE_VERSION = "18"

# Настройки для статических файлов
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Редиректы для SPA поведения
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Обработка 404 ошибок
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Настройки безопасности
[context.production.environment]
  NODE_ENV = "production"